### PR TITLE
Download speed increased

### PR DESCRIPTION
**Pull request by NexoCube**
The thread was running on Core 1, but on core 1 there's a lot of kernel stuff being made in background, i decided to start the thread on Core 0 because on Core 2 every single GX2 stuff is running on it. So :p Enjoy :D

### CODE REVIEW

**Comment by CreeperMario** [comment]
That's seriously all it takes to increase the download speed?!
I think I need a refresher on how threading works...

**Comment by NexoCube** [comment]
Thread were running on core 1 but he was already used by kernel subroutine

Core 2 is used by GX2 stuff

So core 0 was the last candidate, and yeah it's really working.

**Comment by NexoCube** [comment]
Loadiine GX2 took 20 sec to download instead of 40-60 sec (For vgmoose and me)

**Comment by vgmoose** [comment]
Merged, will do a 1.1 release with this change soon!

Thanks!

**Pull request merged**
